#!/usr/bin/env bash
# Transfer a file from our client to a server
# Accepts four (4) paramaeters;
#	1. The path to the file to be transfered
#	2. The IP of the server we want to transfer the file to
#	3. The username scp connects with
#	4. The path to the SSH private key that scp uses

# Checks if the number of arguments is less than 4

if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH-TOSSH_KEY"
  exit 1
fi

# Assign arguments to variables for clarity
PATH_TO_FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"

# Exit with the status of the scp command
exit $?
