#!/usr/bin/env bash
#Displays `Best School` 10 times using a while loop.
#with "Hi" on a new line on the 9th iteration

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( i++ ))
done
