#!/usr/bin/env bash
#Using a while loop, displays `bad luck` on the 4th iteration,
#`good luck` on the 8th iteration, otherwise `Best School`.


i=1

while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	(( i++ ))
done
