#!/usr/bin/env bash
#Configures an Ubuntu server with requirements:
#	- localhost resolves to 127.0.0.2
# 	- facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.bak

echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

grep -v 'localhost\|facebook.com' /etc/hosts | sudo tee -a ~/hosts.new > /dev/null
sudo cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
